### ISSUE TITLE
Build and distribute AppImage of Popsicle

### ISSUE THREAD

**Issue by TheAssassin** [pop-os/popsicle#104]
Providing an [AppImage](https://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](https://docs.appimage.org/user-guide/run-appimages.html#download-make-executable-run), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional [desktop integration](https://docs.appimage.org/user-guide/run-appimages.html#integrating-appimages-into-the-desktop)
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using [AppImageUpdate](https://docs.appimage.org/introduction/software-overview.html#appimageupdate)
- Can optionally sign your AppImages (inside the file) using gpg2
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the [`--appimage-extract`](https://docs.appimage.org/user-guide/run-appimages.html#mount-or-extract-appimages) parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

I've got a PR in preparation to build AppImages with [appimagecraft](https://github.com/TheAssassin/appimagecraft). As a preparation for that PR, another PR is on the way, fixing the desktop entry you already have in this repository.

**Comment by TheAssassin** [comment]
Size of the AppImage built using appimagecraft with the script provided in #106:

```sh
12M	Popsicle_USB_Flasher-1.1.0-4-g5fb10c3-x86_64.AppImage
```

**Comment by mmstick** [comment]
[We are distributed on Flathub](https://flathub.org/apps/details/com.system76.Popsicle) if you happen to have Flatpak.

**Comment by ids1024** [comment]
Offering an appimage alongside flatpak seems like generally a good thing. I suppose the main concern is that it's another thing to maintain and test.

I guess the maintenance required would be fairly minimal if it's automatically built on CI.

**Comment by TheAssassin** [comment]
Being maintainer of AppImage (and considering AppImage a better solution for most of my use cases, especially that an AppImage pretty portable) I'd love to see an AppImage build next to the other builds.

@ids1024 building an AppImage is very easy (in fact, all you need to do is get appimagecraft and run it in your repo root directory) indeed. Most projects automate that task on their CI systems. A popular option is to use Travis CI and upload a new AppImage on every commit, providing a continuous release (e.g., usign https://github.com/probonopd/uploadtool).
I might've included a patch for that, too, but it seems your CI infra is private. Integrating shouldn't be too hard, though.

**Comment by probonopd** [comment]
> We are distributed on Flathub if you happen to have Flatpak.

It doesn't do what AppImage does (one app = one file). So it's complementary.

**Comment by ids1024** [comment]
https://github.com/pop-os/popsicle/releases/tag/1.2.0 has an AppImage attached, automatically built by Github Actions.

**Comment by TheAssassin** [comment]
Yup, seems to work very well. Thanks!
