### ISSUE TITLE
Doesn't even work?

### ISSUE THREAD

**Issue by ergpopler** [pop-os/popsicle#109]
Running popsicle on Pop!_OS and arch results in the same outcome.

When it says Select Drives it lists my hard drive name, but says 0B: Device too small and doesn't list anything else, balena etcher finds my USB just fine.... 

No matter the ISO it just refuses to find my USB...

Using the one preinstalled on Pop! and the appimage on Arch.

**Comment by ids1024** [comment]
Odd, particularly if you're having this issue with the Pop! package. (The AppImage should work too, but has been tested less.)

Is it just a normal USB flash drive? (Rather than a hard drive, SD card reader, or anything like that.)

**Comment by ergpopler** [comment]
it is an sd card usb thing

**Comment by ids1024** [comment]
Ah, then that's probably the issue. I suppose this test in [usb-disk-probe](https://github.com/pop-os/usb-disk-probe/blob/master/src/stream.rs) (on filenames in `/dev/disk/by-path/`) must be returning `false`:

```rust
fn is_usb(filename: &str) -> bool {
    filename.starts_with("pci-") && filename.contains("-usb-") && filename.ends_with("-0:0:0:0")
}
```

Not sure what format that string has for such a device. But it seems it should probably be listed.

Popsicle was semi-recently (https://github.com/pop-os/popsicle/pull/94) updated to use UDisks2 for gaining write access to the drive. It should probably use that for finding USB devices as well.

**Comment by ergpopler** [comment]
damn dis fixed it yayayayaa

**Comment by ids1024** [comment]
Great to have confirmation that it's working well now!

I was already planning to change the way devices are detected to support better sandboxing for the Flatpak.
