### ISSUE TITLE
Placeholder icon on "Flashing Completed" page for theme other than Pop

### ISSUE THREAD

**Issue by ids1024** [pop-os/popsicle#110]
The `process-completed` icon doesn't seem to be present in other themes.

**Comment by TechnologyMan101** [comment]
![image](https://user-images.githubusercontent.com/65311278/98152726-03e9bc00-1e87-11eb-8d42-835fa6f724dd.png)

Same with the normal USB icon too

**Comment by mmstick** [comment]
We could include them as gresources in case the system icons are missing.

**Comment by ids1024** [comment]
I see three icons Popsicle relies on here:
* `drive-removable-media-usb`
* `process-completed`
* `dialog-error`
* `application-x-cd-image`

This seems to be the standard for icon theming, to the extent that there is one: https://developer.gnome.org/icon-naming-spec

Looking at that, and at other themes:
* `drive-removable-media-usb` is not standard, but `drive-removable-media` is. The spec seems to suggest the correct behavior is to fall back to the more general one.
* `dialog-error` is standard, and should always be available.
* `application-x-cd-image` is not standard, though some other mime types are. It also exists in the Humanity theme.
* `process-completed` seems to only be in the Pop theme?
