### ISSUE TITLE
Flatpak version does not have a desktop file

### ISSUE THREAD

**Issue by TechnologyMan101** [pop-os/popsicle#111]
**Distribution (run `cat /etc/os-release`):**
 ```NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

**Related Application and/or Package Version (run `flatpak info com.system76.Popsicle`):**
```
Popsicle - Flash multiple USB devices in parallel

          ID: com.system76.Popsicle
         Ref: app/com.system76.Popsicle/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.0
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.7 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: c0b17a95c21ef3c2a0f6adc76286ba85c6bb812e477ca2ce40550201ef8acf4a
      Parent: b15dc13a1eb4981a4e4bf197497e015407256607ee9f28e42e62c22ed232e2ca
     Subject: Set <icon> tag of appdata (a26e606e)
        Date: 2020-10-28 23:04:00 +0000
```

**Issue/Bug Description:**
Flatpak version of Popsicle does not have a desktop file. Therefore, it cannot be found in the application menu/grid and can only be run using `flatpak run com.system76.Popsicle` or by launching it from something like GNOME Software.

**Steps to reproduce (if you know):**
1. Install the Popsicle Flatpak
2. Navigate to application menu/grid
3. Try to find "USB Flasher" or "Popsicle"
4. It does not exist

**Expected behavior:**
There should be a desktop file that shows up in the application menu/grid.

**Other Notes:**
I have restarted the system already but that did not do anything.

**Comment by ids1024** [comment]
Hm, I thought that was working, but I don't think I've tested that with the Flatpak for the last release.

Can you confirm that other flatpaks you install are showing up in the application launcher as expected?

**Comment by TechnologyMan101** [comment]
I tested last night with GNOME 2048 and that showed up fine even without a reboot.

**Comment by ids1024** [comment]
Yep, it seems I accidentally broke this updating the flatpak for the new release.

**Comment by ids1024** [comment]
Fixed in https://github.com/flathub/com.system76.Popsicle/commit/aedf6a39b95e7f46dffda44085178f18ba2ad8b5, which is now deployed to Flathub. `flatpak upgrade` should pull in the fixed version.

Thanks for catching this!

**Comment by TechnologyMan101** [comment]
Okay, updated and working fine now.

Thanks for fixing this!
