### ISSUE TITLE
Drives not detected

### ISSUE THREAD

**Issue by fosskers** [pop-os/popsicle#119]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`popsicle-1.3.0-1`

**Issue/Bug Description:**

Popsicle doesn't seem to detect USB drives that I insert. Checking logs, I see the following message appear every few seconds:
```
failed to refresh devices: "The name org.freedesktop.UDisks2 was not provided by any .service files"
```
This occurs whether I open `popsicle` with `sudo` or without.

**Steps to reproduce (if you know):**

1. Open `popsicle-gtk`.
2. Choose an ISO and hit `Next`.
3. See no drives present in the list.

**Expected behavior:**

I should be able to see my drives.

**Other Notes:**

I'm not sure what `popsicle` expects with respect to mounting. My system doesn't automount USBs. Would that matter?

**Comment by ids1024** [comment]
As stated in the error message, the latest version of Popsicle requires the UDisks2 daemon to be installed and running (so Popsicle itself doesn't have to run as root, consistent with security best practices).

Though that should probably show an error in the GUI.

> I'm not sure what popsicle expects with respect to mounting. My system doesn't automount USBs. Would that matter?

It's fine if drives aren't automounted. Or if they are, in which case Popsicle will try to unmount before flashing.

**Comment by fosskers** [comment]
I installed this from an AUR package, so I guess that package is missing a `udisks2` dependency.
