### ISSUE TITLE
Set up AppImageUpdate

### ISSUE THREAD

**Issue by TheAssassin** [pop-os/popsicle#121]
The Popsicle AppImage works great. However, AppImageUpdate should be set up to allow users to easily update on new releases. All that needs to be done is:

- set the environment variable `UPD_INFO` before calling appimagetool (when using linuxdeploy with `--output appimage`, you have to set it before that) to `gh-releases-zsync|pop-os|popsicle|latest|Popsicle_USB_Flasher-*.AppImage`
- upload the now-created `.zsync` file along with the AppImage (typically, you just need to change the pattern from `...AppImage` to `...AppImage*`

For uploading, you may want to switch to https://github.com/TheAssassin/pyuploadtool/. Then, the build job can then be run on every commit to build a continuous release. pyuploadtool uploads the files to a prerelease called "continuous" when building commits and releases called like the tag when building tags.

**Comment by mmstick** [comment]
Would you be willing to submit these changes as a PR?

**Comment by TheAssassin** [comment]
Done. See #141. It's not 100% complete, but you can easily complete it.
