### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/popsicle#13]
I know we talked about renaming to something else (`Pop! USB Flasher`? `Popsicle`?), so we should: 

- [x] Decide what that's going to be, then
- [x] Rename the repo, and
- [x] Find/replace any relevant bits in the project

**Comment by jackpot51** [comment]
I strongly like the Popsicle name, as it implies sticks, and it lends itself to a great logo - perhaps a popsicle with a USB connector.

**Comment by WatchMkr** [comment]
I like Popsicle too. However, users should be able to determine what an application does when browsing the Utilities folder. We can do something like Totem/Videos. Set the .desktop file name to USB Flasher but the app/commands are popsicle.

**Comment by jackpot51** [comment]
Yep, sounds good @WatchMkr !

**Comment by jackpot51** [comment]
@mmstick this is the last issue before we release "muff" soon to be popsicle.

**Comment by mmstick** [comment]
Alright, I'll look into renaming everything soon. I'll have a PR posted later today.
