### ISSUE TITLE
Missing translation string

### ISSUE THREAD

**Issue by francarotti** [pop-os/popsicle#139]
**Distribution:**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
 
**Related Application and/or Package Version:**
```
popsicle:
  Instalado: 1.3.0~1620573834~20.10~a6c9a16
  Candidato: 1.3.0~1620573834~20.10~a6c9a16
  Tabela de versão:
 *** 1.3.0~1620573834~20.10~a6c9a16 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:** 

The `Done` element to close popsicle after a successful flash doesn't have a translation string. I checked `i18n/en` folder and there isn't a line for this element.

![print-done-popsicle](https://user-images.githubusercontent.com/48105235/117991892-d8073180-b314-11eb-99f2-a39d4855c17b.png)

**Expected behavior:**

This element should be translatable to a user native language. 

**Other Notes:**

I'm really glad of the internalization efforts and hope to be able to contribute in future applications.

**Comment by mmstick** [comment]
Fixed by d3e0ffd4e87fa6c6a0c9eb36d14e3b3ab5073d22
