### ISSUE TITLE
popcicle start on it's own when using android platform tools.

### ISSUE THREAD

**Issue by abs0023** [pop-os/popsicle#149]
It is a little bit annoying that popcicle start on it's own when using fastboot.
especially when i just want to boot from a file and not flashing it.
Could you make popcicle staying out of the way when using android platform tools.
Plus I never installed it myself it must have come along with an update, ( I'm using popos ), I wasn't even aware of it untill it shows by itself.
Sorry, I don't mean bad words, just annoyed.

**Comment by mmstick** [comment]
What do you mean? Popsicle does not start on it's own when using fastboot.

**Comment by abs0023** [comment]
Well i typed;
fastboost boot example.img
then  popcicle poped up.

**Comment by mmstick** [comment]
Applications on Linux cannot start themselves like that. You would have to have run `popsicle-gtk example.img`, or had used Nautilus to open the img file with the default `.desktop` associated with the img format.

**Comment by abs0023** [comment]
Thanks for your time, and sorry for bothering.

**Comment by abs0023** [comment]
I'm sorry. there never been a probleme ever, I'm just the worst idiot ever. sincere apologie.
