### ISSUE TITLE
Run GUI as normal user

### ISSUE THREAD

**Issue by jackpot51** [pop-os/popsicle#16]
This places popsicle in the right context to allow them to browse for an ISO. Upon flashing, launch a command line executable with pkexec and use a pipe to read the status for each drive back into the GUI.

**Comment by brs17** [comment]
Noticed since popsicle currently runs with elevated privileges, the "Open" dialog displays mounting options for `/` as well as `/boot/efi`. The name of an external drive may also be the technically defined name (perhaps the UUID) instead of the generic "8.0 GB Volume".

**Comment by mmstick** [comment]
Would it be possible to do this?

- Launch the application with pkexec
- Create a secondary thread which does all the work as root
- Have the main thread revert back to the original user and initialize GTK there.

**Comment by mmstick** [comment]
I think Wayland's issue is with applications that run UIs that interface with Wayland as root, so if we can separate the components that require root into a separate thread, and then revert permissions back to the user that called pkexec in the main thread before initializing GTK, then this _might_ make it work on Wayland.

I'm not certain of that though, so I'd have to try it out.
