### ISSUE TITLE
Apt or pop issues. (new install) not sure.

### ISSUE THREAD

**Issue by reedrainer** [pop-os/popsicle#174]
Hi im a new user and Ive run into an issue straight away. Its probably an easy fix but i would appreciate a point in the right direction if possible.

'''reed@pop-os:~$ sudo apt update
[sudo] password for reed: 
Hit:1 http://us.archive.ubuntu.com/ubuntu impish InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu impish-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease
Hit:4 http://apt.pop-os.org/proprietary impish InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease
Hit:6 http://apt.pop-os.org/release impish InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
reed@pop-os:~$ sudo apt upgrade -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-image-5.15.23-76051523-generic linux-modules-5.15.23-76051523-generic
The following packages will be upgraded:
  firefox libarchive13 linux-generic linux-headers-generic linux-image-generic
  linux-libc-dev linux-system76 mount popsicle popsicle-gtk system76-scheduler
11 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
3 standard security updates
Need to get 151 MB/151 MB of archives.
After this operation, 447 MB of additional disk space will be used.
Ign:1 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 mount amd64 2.36.1-8ubuntu2.2
Ign:2 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 libarchive13 amd64 3.4.3-2ubuntu0.1
Ign:3 http://apt.pop-os.org/release impish/main amd64 linux-image-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:4 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 firefox amd64 97.0+build2-0ubuntu0.21.10.1
Ign:1 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 mount amd64 2.36.1-8ubuntu2.2
Ign:5 http://apt.pop-os.org/release impish/main amd64 linux-modules-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:2 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 libarchive13 amd64 3.4.3-2ubuntu0.1
Ign:4 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 firefox amd64 97.0+build2-0ubuntu0.21.10.1
Ign:6 http://apt.pop-os.org/release impish/main amd64 linux-libc-dev amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:7 http://apt.pop-os.org/release impish/main amd64 popsicle amd64 1.3.0~1644434960~21.10~cb67092
Ign:1 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 mount amd64 2.36.1-8ubuntu2.2
Ign:2 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 libarchive13 amd64 3.4.3-2ubuntu0.1
Ign:8 http://apt.pop-os.org/release impish/main amd64 popsicle-gtk amd64 1.3.0~1644434960~21.10~cb67092
Ign:4 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 firefox amd64 97.0+build2-0ubuntu0.21.10.1
Ign:9 http://apt.pop-os.org/release impish/main amd64 system76-scheduler amd64 1.0.0~1644260140~21.10~a0a25ea
Ign:3 http://apt.pop-os.org/release impish/main amd64 linux-image-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:5 http://apt.pop-os.org/release impish/main amd64 linux-modules-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:1 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 mount amd64 2.36.1-8ubuntu2.2
Err:1 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 mount amd64 2.36.1-8ubuntu2.2
  Connection failed [IP: 91.189.91.38 80]
Ign:6 http://apt.pop-os.org/release impish/main amd64 linux-libc-dev amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:2 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 libarchive13 amd64 3.4.3-2ubuntu0.1
Ign:4 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 firefox amd64 97.0+build2-0ubuntu0.21.10.1
Ign:7 http://apt.pop-os.org/release impish/main amd64 popsicle amd64 1.3.0~1644434960~21.10~cb67092
Err:2 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 libarchive13 amd64 3.4.3-2ubuntu0.1
  Connection failed [IP: 91.189.91.38 80]
Err:4 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 firefox amd64 97.0+build2-0ubuntu0.21.10.1
  Connection failed [IP: 91.189.91.39 80]
Ign:8 http://apt.pop-os.org/release impish/main amd64 popsicle-gtk amd64 1.3.0~1644434960~21.10~cb67092
Ign:9 http://apt.pop-os.org/release impish/main amd64 system76-scheduler amd64 1.0.0~1644260140~21.10~a0a25ea
Ign:3 http://apt.pop-os.org/release impish/main amd64 linux-image-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:5 http://apt.pop-os.org/release impish/main amd64 linux-modules-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:6 http://apt.pop-os.org/release impish/main amd64 linux-libc-dev amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
Ign:7 http://apt.pop-os.org/release impish/main amd64 popsicle amd64 1.3.0~1644434960~21.10~cb67092
Ign:8 http://apt.pop-os.org/release impish/main amd64 popsicle-gtk amd64 1.3.0~1644434960~21.10~cb67092
Ign:9 http://apt.pop-os.org/release impish/main amd64 system76-scheduler amd64 1.0.0~1644260140~21.10~a0a25ea
Err:3 http://apt.pop-os.org/release impish/main amd64 linux-image-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
  Connection failed [IP: 52.38.47.2 80]
Err:5 http://apt.pop-os.org/release impish/main amd64 linux-modules-5.15.23-76051523-generic amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
  Connection failed [IP: 52.38.47.2 80]
Err:6 http://apt.pop-os.org/release impish/main amd64 linux-libc-dev amd64 5.15.23-76051523.202202110435~1644952300~21.10~96763f1
  Connection failed [IP: 52.38.47.2 80]
Err:7 http://apt.pop-os.org/release impish/main amd64 popsicle amd64 1.3.0~1644434960~21.10~cb67092
  Connection failed [IP: 52.38.47.2 80]
Err:8 http://apt.pop-os.org/release impish/main amd64 popsicle-gtk amd64 1.3.0~1644434960~21.10~cb67092
  Connection failed [IP: 52.38.47.2 80]
Err:9 http://apt.pop-os.org/release impish/main amd64 system76-scheduler amd64 1.0.0~1644260140~21.10~a0a25ea
  Connection failed [IP: 52.38.47.2 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/util-linux/mount_2.36.1-8ubuntu2.2_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/liba/libarchive/libarchive13_3.4.3-2ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://apt.pop-os.org/release/pool/impish/linux/96763f1cb88ac5896ebc5449b1c56d746abdd12e/linux-image-5.15.23-76051523-generic_5.15.23-76051523.202202110435%7e1644952300%7e21.10%7e96763f1_amd64.deb  Connection failed [IP: 52.38.47.2 80]
E: Failed to fetch http://apt.pop-os.org/release/pool/impish/linux/96763f1cb88ac5896ebc5449b1c56d746abdd12e/linux-modules-5.15.23-76051523-generic_5.15.23-76051523.202202110435%7e1644952300%7e21.10%7e96763f1_amd64.deb  Connection failed [IP: 52.38.47.2 80]
E: Failed to fetch http://apt.pop-os.org/release/pool/impish/linux/96763f1cb88ac5896ebc5449b1c56d746abdd12e/linux-libc-dev_5.15.23-76051523.202202110435%7e1644952300%7e21.10%7e96763f1_amd64.deb  Connection failed [IP: 52.38.47.2 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/f/firefox/firefox_97.0%2bbuild2-0ubuntu0.21.10.1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://apt.pop-os.org/release/pool/impish/popsicle/cb670925e558e9609cb3ed7b4772532ed417ff05/popsicle_1.3.0%7e1644434960%7e21.10%7ecb67092_amd64.deb  Connection failed [IP: 52.38.47.2 80]
E: Failed to fetch http://apt.pop-os.org/release/pool/impish/popsicle/cb670925e558e9609cb3ed7b4772532ed417ff05/popsicle-gtk_1.3.0%7e1644434960%7e21.10%7ecb67092_amd64.deb  Connection failed [IP: 52.38.47.2 80]
E: Failed to fetch http://apt.pop-os.org/release/pool/impish/system76-scheduler/a0a25eaa7c3b583501039eb800cf31b1cac15223/system76-scheduler_1.0.0%7e1644260140%7e21.10%7ea0a25ea_amd64.deb  Connection failed [IP: 52.38.47.2 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
'''

**Comment by reedrainer** [comment]
Ive gone through a few things trying to sort it out. eg 
'''sudo apt --fix-broken install
sudo apt clean
sudo apt update -m
sudo dpkg --configure -a
sudo apt install -f
sudo apt full-upgrade
sudo apt autoremove --purge'''

Its still an issue. Part of me is wondering if there's a connection issue at my end but I feel like ive run into issues with this before on Ubuntu and it was a REALLY simple fix.

**Comment by jacobgkau** [comment]
Getting connection failed for both the Canonical-hosted Ubuntu servers and the System76-hosted Pop!_OS servers at the same time does point to a network connection issue on your end. Are you able to access http://apt.pop-os.org/ and http://us.archive.ubuntu.com/ in a web browser?
