### ISSUE TITLE
Local build instructions

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/popsicle#18]
It would be useful to add local development and building instructions to the README so others can contribute.

**Comment by mmstick** [comment]
It's just a matter of installing the `libgtk-3-dev` package (if building the GTK3 frontend), as well as`cargo`, then running `make`. `make cli` will build just the CLI, so no dependencies required (could even be built with the MUSL toolchain, for a fully static binary). `make gtk` will build just the GTK frontend.

`make cli` is mainly just running `cargo build --release --manifest-path cli/Cargo.toml`, and `make gtk` is running `cargo build --release --manifest-path gtk/Cargo.toml`. The `--manifest-path` flag just specifying to build the workspace specified by the path to its Cargo.toml file.
