### ISSUE TITLE
`popsicle` CLI hangs, but finishes flashing USB

### ISSUE THREAD

**Issue by leviport** [pop-os/popsicle#201]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
popsicle:
  Installed: 1.3.2~1689262463~22.04~5ebc062
  Candidate: 1.3.2~1689262463~22.04~5ebc062
  Version table:
 *** 1.3.2~1689262463~22.04~5ebc062 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Popsicle's CLI interface no longer displays the progress bar, or completes and closes after flashing a USB. Instead, it just hangs with no output until the user cancels it with Ctrl+C. Given enough time, flashing does complete and the USB is in the expected state, but Popsicle never terminates. It just sits at this point until killed:
![2023-07-21_11-55-18](https://github.com/pop-os/popsicle/assets/13512097/396f79fc-bed5-4a46-9afa-c387e7f44d39)

**Steps to reproduce (if you know):**
Flash an ISO to a USB with `popsicle` in a terminal

**Expected behavior:**
Progress bar is displayed, and Popsicle terminates when complete.

**Other Notes:**

**Comment by ids1024** [comment]
Seems `pbr 1.1` caused the issue here: https://github.com/a8m/pb/pull/120
