### ISSUE TITLE
Hash freezes the application

### ISSUE THREAD

**Issue by alex285** [pop-os/popsicle#30]
**Reproduce**
1. Open Popsicle
2. Choose Image
3. Change Hash type either to SHA256 or MD5

**Outcome:** Until it generates the Hash, the whole application freezes. We cant even move the window

4. Assuming we previously had selected SHA256, **select MD5 now**
5. Application freezes again
6. Reselect SHA256

**Outcome:** Application again freezes, and i guess it tries to re-generate the hash, when it already knows it from previous generation

The "freeze" is for 3-4 seconds, so it is not unnoticeable

**Comment by mmstick** [comment]
Will try to resolve within the next 24 hours.
