### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by brs17** [pop-os/popsicle#33]
Pop!_OS 18.04 (iso 12 with updates run)

top shows a >100% CPU usage when launching popsicle (on Bonobo 13 or Galago Pro 3). This is not during the writing of an image but just with the application open.

**Comment by mmstick** [comment]
I may have an idea of why that's happening. I'll look into it later today.

**Comment by brs17** [comment]
Tomorrow would also be acceptable @mmstick
