### ISSUE TITLE
Disable FLASH button if no device is selected

### ISSUE THREAD

**Issue by Alecaddd** [pop-os/popsicle#37]
I accidentally clicked the `NEXT` button twice and triggered the `FLASH` button, which is in the same location on the final screen.
The action was triggered without me selecting any device to flash the ISO, so the app was stuck on the final screen with no action running, and no way to go back.
I'd suggest disabling the `FLASH` button if no device has been selected.
Also, a confirmation message before proceeding would add a layer of security in case of accidental clicks.
Great little app!

**Comment by mmstick** [comment]
I'll see about getting this fixed today. I wrote most of the code (and some refactoring) yesterday.
