### ISSUE TITLE
Consider pushing to crates.io.

### ISSUE THREAD

**Issue by c-edw** [pop-os/popsicle#40]
Pushing `popsicle` to [crates.io](crates.io) would allow people to easily install it through just a `cargo install`.

**Comment by mmstick** [comment]
The issue with installing via `cargo` is that you won't get the policykit or desktop files. Or any other assets that Popsicle might ship. The provided Makefile & debian packaging is way to go for installing this.

**Comment by c-edw** [comment]
@mmstick Correct, but I still think the CLI utility is worth being on crates.io. Although more inconvenient, I install a lot of Rust utilities from there, and I believe others do also.

**Comment by mmstick** [comment]
Which Linux distro do you use? Maybe we could get it packaged in some way.

**Comment by c-edw** [comment]
@mmstick Ubuntu 18 for the most part. It would be nice to have `popsicle` as a Debian package for sure.

**Comment by isantop** [comment]
FWIW, having Popsicle packaged in Debian is probably the easiest way to get it into Ubuntu as well. We couldn't keep it as up-to-date as we can in Pop, but wanting to have it available is definitely something that I heard echoed a bit at LFNW.
