### ISSUE TITLE
Writing image bigger than USB

### ISSUE THREAD

**Issue by BobyMCbobs** [pop-os/popsicle#46]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
popsicle:
  Installed: 0.1.5~1526005323~18.04~9254724
  Candidate: 0.1.5~1526005323~18.04~9254724
  Version table:
 *** 0.1.5~1526005323~18.04~9254724 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Popsicle allows writing a bigger image than the capacity of the USB without warning the user.

**Expected behavior:**
A prompt should appear saying that this operation cannot be done since the size of the image is bigger than the USB.

**Comment by mmstick** [comment]
Rather than a prompt, I'll simply make the devices unselectable.

**Comment by WatchMkr** [comment]
With a hint would be good as well (Device too small).

**Comment by brs17** [comment]
@mmstick A possible concern I have regarding making devices that are too small not appear, is that a user would not necessarily understand why a device is not showing up and then possibly worry about a bad usb drive or the like.

**Comment by mmstick** [comment]
@brs17 The PR (https://github.com/pop-os/popsicle/pull/47) displays "Device is too small" in the label of the device's GtkCheckButton, as well as within the tooltip for that button, so it should be okay.

**Comment by BobyMCbobs** [comment]
Yeah, that looks informative how it should be!

**Comment by brs17** [comment]
PR was just merged, fix should be out in the wild soonish!
