### ISSUE TITLE
popiscle-gtk using 100% CPU while waiting for iso

### ISSUE THREAD

**Issue by sklei4** [pop-os/popsicle#50]
I was downloading an ISO to flash on a USB when I noticed the fan spinning louder than I've ever heard it before. I checked top to see if someone was using the CPU. popiscle-gtk came in first with 100% of the CPU being used.

**Comment by mmstick** [comment]
I'll check it out.

**Comment by mmstick** [comment]
This commit (https://github.com/pop-os/popsicle/commit/2ba9db3d26a3ffce6ec93d4232a318fab138878d) will fix it. It will be in the repos shortly.

**Comment by sklei4** [comment]
Awesome. I get my OS updated on GitHub. Thank you.
