### ISSUE TITLE
Internal drive recognized as USB device

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/popsicle#7]
Internal hard drive is being recognized as a usb device making the `-a` flag not work properly.

Error message:
```
unmounting '/dev/disk/by-path/pci-0000:00:14.0-usb-0:12:1.0-scsi-0:0:0:0': "/dev/sdc1" is mounted at "/media/[redacted]/Pop_OS 17.10 amd64"
muff: error opening disk '/dev/disk/by-path/pci-0000:00:14.0-usb-0:14:1.0-scsi-0:0:0:0': No medium found (os error 123)
```
Disks info of drive:
![disks](https://user-images.githubusercontent.com/4884946/37374433-bda72f70-26e0-11e8-924f-b7d1bb8db821.png)

Any idea why this is going on?

**Comment by mmstick** [comment]
That is pretty odd, for an internal drive to be recognized as a USB device by Linux.

What's the output of the following?

```sh
cat /sys/block/sdb/removable
```

**Comment by ahoneybun** [comment]
cat /sys/block/sdb/removable
0

**Comment by jackpot51** [comment]
Aaron are you sure? I think it found something like an empty SD card slot, unless your SSD is connected over USB

**Comment by jackpot51** [comment]
It says sdc, not sdb:

'/dev/disk/by-path/pci-0000:00:14.0-usb-0:12:1.0-scsi-0:0:0:0': "/dev/sdc1"

**Comment by ahoneybun** [comment]
I did not have any SD card plugged in.

**Comment by ahoneybun** [comment]
Fixed!
