### ISSUE TITLE
Invalid MIME type

### ISSUE THREAD

**Issue by kpuljek** [pop-os/popsicle#79]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

<pre>popsicle:
  Installed: 0.1.5~1560357257~19.04~3d3d410
  Candidate: 0.1.5~1560357257~19.04~3d3d410
  Version table:
 *** 0.1.5~1560357257~19.04~3d3d410 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
</pre>

**Issue/Bug Description:**

Recently started getting this error while updating the system (I could probably pinpoint when, but it would take some time)

```
Error in file "/usr/share/applications/com.system76.Popsicle.desktop": ""application/x-cd-image" is an invalid MIME type (""application" is an unregistered media type)
Error in file "/usr/share/applications/com.system76.Popsicle.desktop": """ is an invalid MIME type (""" does not contain a subtype)
```

Comparing to other .desktop files, I noticed others don't have the quotation marks around their MIME types, so I removed them manually and the error is gone (probably until the next update)

**Steps to reproduce (if you know):**

Run a system update from the terminal (apt update && apt upgrade)

**Expected behavior:**

No errors

**Other Notes:**

**Comment by whereswaldon** [comment]
Yeah, I just swung by to report the same thing. Drives me nuts to see this on every package update. I'll submit a PR to remove them.
