### ISSUE TITLE
Popsicle fails to compile with "error[E0308]: mismatched types"

### ISSUE THREAD

**Issue by Wychmire** [pop-os/popsicle#83]
**Distribution (run `cat /etc/os-release`):** Void Linux
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Popsicle, latest git commit. (r202.e714aab)

**Issue/Bug Description:**  Compiling Popsicle errors with
```
   Compiling popsicle_gtk v0.2.0 (https://github.com/pop-os/popsicle#e714aab4)
error[E0308]: mismatched types
  --> /home/caleba/.cargo/git/checkouts/popsicle-7ad9519ffbbd5284/e714aab/gtk/src/app/widgets/dialogs.rs:23:15
   |
23 |             | path.map(|p| dialog.set_current_folder(p));
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- help: consider using a semicolon here
   |               |
   |               expected (), found enum `std::option::Option`
   |
   = note: expected type `()`
              found type `std::option::Option<bool>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `popsicle_gtk v0.2.0 (https://github.com/pop-os/popsicle#e714aab4)`, intermediate artifacts can be found at `/tmp/cargo-installdq73uK`

Caused by:
  could not compile `popsicle_gtk`.
```

**Steps to reproduce (if you know):** Run `cargo install --git https://github.com/pop-os/popsicle popsicle_gtk`, failure on step 153: `Compiling popsicle_gtk v0.2.0 (https://github.com/pop-os/popsicle#e714aab4)`

**Expected behavior:** Popsicle compiles without error and successfully runs.

**Other Notes:** While I have all the dependecies listed on the README installed, this [AUR](https://aur.archlinux.org/pkgbase/popsicle-git/#comment-721539) comment suggests I might need other packages installed. Even with `xorgproto` installed it still fails however.

Compiling 0.1.5 works, but results in a single binary, `muff`, which appears to CLI only.

**Comment by mmstick** [comment]
https://github.com/pop-os/popsicle/pull/82 is about to be merged, so you can try that.

It should still compile though as long as you haven't updated the lock file, and have the minimum required Rust version.

**Comment by Wychmire** [comment]
I couldn't figure how to get Cargo to clone/build from a different branch so I manually cloned the repo and compiled from the async branch with `make gtk`. Successfully compiles and runs! Hoping it gets merged into master soon.

**Comment by mmstick** [comment]
This project can't be compiled or installed directly with Cargo. You have to use the Makefiles for building and installing. Otherwise you miss out on all of the required assets that the GTK application needs in the system.

**Comment by mmstick** [comment]
The PR has been merged
