### ISSUE TITLE
Error 127 on install from cloned repo

### ISSUE THREAD

**Issue by LincolnAuster** [pop-os/popsicle#87]
**Distribution (run `cat /etc/os-release`):**
 Manjaro Linux
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Cloned popsicle repo

**Issue/Bug Description:**
cargo build --manifest-path gtk/Cargo.toml --release
make: cargo: No such file or directory
make: *** [Makefile:118: target/release/popsicle-gtk] Error 127

on make && sudo make install

**Steps to reproduce (if you know):**
Clone the repo, sudo make && sudo make install

**Expected behavior:**
I'd assume the command should install popsicle

**Comment by AleSprea97** [comment]
Same thing on Ubuntu 20.04. P.S. "cargo -V" outputs "cargo 1.39.0 (1c6ec66d5 2019-09-30)" so I think that cargo is installed.

**Comment by mmstick** [comment]
Looks like Cargo is not in your PATH. Make sure that your Makefile has access to the cargo binary.
