### ISSUE TITLE
Disk sizes are not shown in the UI

### ISSUE THREAD

**Issue by strycore** [pop-os/popsicle#91]
The disk selection dialog can be a little confusing for users, especially when some drives have a generic name.

![Screenshot from 2020-07-06 15-33-13](https://user-images.githubusercontent.com/280336/86659036-621c9600-bf9e-11ea-8b69-90336587fcd3.png)

Here, I have an option between the SD card I want to flash and my 8TB backup drive that contains a lot of very important data.
Having the size of the drive displayed could make the distinction between drives clearer. 
As a bonus, it would be also nice to have a visual warning for large drives in the same way Etcher has.

**Comment by jacobgkau** [comment]
@ids1024 just merged https://github.com/pop-os/popsicle/pull/90 for this last Thursday. It looks like the update has been released:

![popsicle-i91](https://user-images.githubusercontent.com/7199422/86795350-b1a8a380-c02a-11ea-908b-999a83bd7b68.png)

Can you please install all updates from the Pop!_Shop and then restart Popsicle? If you're still not seeing the sizes displayed, please provide the output of these commands:

```
sudo apt update
apt policy popsicle
```

**Comment by strycore** [comment]
Thanks, I upgraded to the latest build and it shows disk size :)
