### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by ids1024** [pop-os/popsicle#93]
As mentioned in https://github.com/pop-os/popsicle/issues/89, Fedora Media Writer is available as a Flatpak, and uses the `org.freedesktop.UDisks2` dbus service to get permission through Polkit.

`pkexec` isn't available in a Flatpak sandbox, so as far as I can tell, doing the same thing is the best way to make Popsicle run in a Flatpak. If we don't want to use this method on Pop!_OS (since it would request a password for each device that's flashed, for instance), it can be supported as one mode. For instance, it could be added to the current design when not run as root (currently, `popsicle-gtk` seems to not work when not started as root, but doesn't  display an error to indicate the issue.)

By default, it's also not possible to use `/dev` to find USB devices. Fedora Media Writer uses the `org.freedesktop.DBus.ObjectManager` interface on `/org/freedesktop/UDisks2` to scan for devices, but using `--device=all`, the current `UsbDiskProbe` code works in a Flatpak.

**Comment by ids1024** [comment]
It looks like if we want to make Popsicle available on Flathub, we'll need a tagged release, with a `<version>` tag in the appdata.

https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds
https://github.com/flathub/flathub/wiki/App-Requirements#appstream

**Comment by mmstick** [comment]
We now have a tagged release

**Comment by ids1024** [comment]
https://flathub.org/apps/details/com.system76.Popsicle

**Comment by pizzadude** [comment]
@ids1024 https://github.com/flathub/com.system76.Popsicle/issues/1
